* Oppgave
- Build own Effective field theory that approximates the phase shifts from project1
- Follows article
- Pionless EFT to describe nucleon-nucleon scattering at low energies.
  - A series of contact interactions
  - domain of effective range expansion
  - valid up to onshell-momentum k ~ m_pi / 2, about 10 MeV lab energy
- Contact interactions look complicated, but are simplified wehn striking spin/isospin matrices.
- Start by fitting the lowest order pionless interaction model.
- For 1S0 channel, V1^LO(p, p') = C0
  - Coupling constants are linear combinations of the coupling constants in the general expression
  - Naively applied gives UV divergence, need regularization
  - Sharp cutoff, tricky. Can give Gibbs overshot phenomena
  - Use a smooth UV regulator V(p', p) = fl(p')V(p',p)fl(p)
    with fl(p) = exp(-p^4/l^4)
- Choose an appropriate value for Lambda and fit C0 to low energy phase shift
- *Pionless, adding next order*
  - V^NLO(p', p) = C2(p^2 + p'^2)
  - Fit the parameters C0, C2 to the low energy phase shifts from project 1.
- V^NNLO(p', p) = C4(p^4 + p'^4) + C'4p²p'²
  + Fit the four parameters C0, C2, C4, C'4 to the low-energy phase shifts.
  + Make plot of LO, NLO, NNLO phase shifts and compare them to the results from Project1 potential.
  + Make a plot like Figure 3 in Lepage to show the power-low improvement with each additional order
    From this, pick off the breakdown scale of Lambda_b where EFt stops improving with additional orders.
    - "Lepage plots", showing where EFT is working as expected.
  + Repeat NLO pionless fits for several different values of Lambda
  + Make analogous plots to Fig. 4 in Lepage
  + Commenct on error scaling
- Lambda >> Lambda_b doesn't but anything, as the errors scale by
  Delta(Q) ~ Max((Q/Lambda)^n, (Q/Lambda_b)^2)
- *One-pion exchange term*
- We expect Lambda_b ~ m_pi
- Want to build a toy EFT which works at higher energies.
- Include longest ranged Yukawa potential as an explicit degree of freedom in our EFT
-+ Repeat 2a-2b) by including the simple one-pion exchange contribution and refit contact term couplings
- VLO(p,p') = Vpi(p,p') + C0
- VNLO(p,p') = Vpi(p,p') + C0 + C2(p² + p²')
- With analogous form for the NNLO potential(?)
  - Jeg antar V^NNLO(p',p) = Vpi(p,p') + C0 + C4(p^4 + p'^4) + C'4p²p'²
  + Redo 2a-2b, modify Lambda to appropriate value
  + Redo analysis of 2C, comment on similarities/differences

    
* Notates
  - Low energy behavior is independent of the details of the short-distance dynamics
    - Scattering process insensitive to the details of the potential
    - Can replace the short distance potential with a simpler form to simply calculation without loss
  - Nucleons interact by exchanging pion particle.
    - At low energies the interaction can described by a contact potential (delta potential)
  - Using a simpler potential in LS can result in UV divergence, need
    regularization to cut off the high-momentum modes.
    
* Møte
Hei:)
Jeg vet ikke helt hvor jeg skal begynne.
Jeg har slitt mentalt den siste tiden
Jeg har fortsatt ikke fått gjort ferdig spesialpensum, selv med hele sommeren på
meg. Det er bare så himmla teit
  

* Notat pt2
   Start with pionless EFT. Longest range piece of the potential is unresolved.
   EFT is just a series of contact potentials. Range of effective range expansion
   valid up to an onshell momentum k~mpi/2 = 10 MeV lab energy. 
   Lowest pionless interaction
          VLO(q,p) = C0
   p 32-33 of Machleidt
   
   Potential gives UV divergences if used in LS. Use a smooth UV regulator
         V(q, p) => fLambda(q)V(q,p)fLambda(p)
   * Pick appropriate value for lambda and fit C0
     

   Add NLO and NNLO. Fit C0, C2, C4, C4'. 
   * Plot LO, NLO, NNLO and compare to p1.
   * Make fig 3 in lepage
   * Pick breakdown scale lambda_b where EFT stops impriving
   * Make fig 4 in lepage. Explain dependence on Lambda and Lambdab
  Pionless EFT reproduces the physics of effective range expansion, expect
  lambda_b approx m_pi. Sets the scale of the longest ranged yukawa term.
  * Redo a-b with pion term, modifying lambda to an appropriate value.
    Expect lambda_b to be at a higher value, roughly equal to the mass of
    the next heaviest Yukawa term.
  * Redo 2c, the cutoff dependence

* Fit parameters
** 0.1 MeV
   *** NLO
 * Candidate solution
    Final objective value:     2.700915e-04

 * Found with
    Algorithm:     SAMIN

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 0.0e+00

 * Work counters
    Seconds run:   1516  (vs limit 1800)
    Iterations:    80051
    f(x) calls:    80051
    ∇f(x) calls:   0
, [-0.5400927768854299, 0.04593368271175204])
   LBFGS only finds -0.53, 0.03


   Another solution:
 * Candidate solution
    Final objective value:     3.870819e-03

 * Found with
    Algorithm:     Particle Swarm

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 1.0e-08

 * Work counters
    Seconds run:   241  (vs limit 240)
    Iterations:    249
    f(x) calls:    12700
    ∇f(x) calls:   0
, [-0.5428064060592137, 0.059616093970752466])

 * Candidate solution
    Final objective value:     7.773655e-03

 * Found with
    Algorithm:     Particle Swarm

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 1.0e-08

 * Work counters
    Seconds run:   601  (vs limit 600)
    Iterations:    302
    f(x) calls:    30503
    ∇f(x) calls:   0
, [-0.5462310625489469, 0.07693822069153569])

  BBOptim seems to find the best solution:
  Best candidate found: [-0.540093, 0.0459337]

  Fitness: 0.000270091
** 1 MeV
   *** NLO
       Annealing in [-1, -1] [1, 1] [-0.5, 0.5] loss 1.2e-3, 1555 sec conv
       [-0.53702320331934, 0.030541556807411496] 
   *** NNLO
       Seems to be several local minima where it is easy to get stuck.
 * Candidate solution
    Final objective value:     1.134094e-02

 * Found with
    Algorithm:     SAMIN

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 0.0e+00

 * Work counters
    Seconds run:   3391  (vs limit 7200)
    Iterations:    160401
    f(x) calls:    160401
    ∇f(x) calls:   0
, [-0.5450058383260756, 0.10739601096353377, 0.002847804378870855, -0.7532750321029799])
  rt = 0.99
 * Work counters
    Seconds run:   7200  (vs limit 7200)
    Iterations:    342808
    f(x) calls:    342808
    ∇f(x) calls:   0
, [-0.540098728827698, -0.05414519007866481, 0.30582883298169583, 0.4771116809792675])

* Notat 3
** The couplings are equivalent to the multipole moments
** Contact terms mimic the short range behavior.
** Pion terms mimic the long range behavior
** Coupling constants must compensate. running
** Coupling constants vary alot when the short range potential is strong
** When the cutoff is very large, larger than the long range potential or if the
   the long range potential is missing, the coefficients will tend to a constant
** Cutoff too short -> wavelengths too long to probe the true structure of the potential
   Often introduce non-linearity in the coefficients, may become untuneable
** Why tune at low energies? Minimize effect of a^6 (ogslike) large error behavior
** We restrict ourselves to np scattering to avoid pp Coloumb
** Phase shifts are not really data - they must be extracted through some theoretical procedure.
   Experimental errors are difficult to interpet
** Lepage sjekker \Lambda fra 50 til 400 MeV
** Compare different terms as done in Lepage fig 7
** Expect powers to grow by \Lambda² because that is how the powers of p in the terms are.
    If NLO grows like E^(0.5), expect NNLO to grow like E^(0.5+2)
** Lepage doesn't fit as low as me, approx 0.2
** Our omitted 2pion terms are of the same order as p4
   We expect? that err(2pion) < err(1pion)
** Lepage 350 MeV, 150 MeV without pion. Tuned at 0.1 MeV
** Values of the coupling coefficients can in principle be derived from QCD
    

  
